# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.bgp_actions import BGPActions

class TestBGPActions(unittest.TestCase):
    """BGPActions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBGPActions(self):
        """Test BGPActions"""
        # inst = BGPActions()

if __name__ == '__main__':
    unittest.main()
