# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.cloud_router_change_type import CloudRouterChangeType

class TestCloudRouterChangeType(unittest.TestCase):
    """CloudRouterChangeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudRouterChangeType(self):
        """Test CloudRouterChangeType"""
        # inst = CloudRouterChangeType()

if __name__ == '__main__':
    unittest.main()
