# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.expression_operator import ExpressionOperator

class TestExpressionOperator(unittest.TestCase):
    """ExpressionOperator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpressionOperator(self):
        """Test ExpressionOperator"""
        # inst = ExpressionOperator()

if __name__ == '__main__':
    unittest.main()
