# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.provider_status import ProviderStatus

class TestProviderStatus(unittest.TestCase):
    """ProviderStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderStatus(self):
        """Test ProviderStatus"""
        # inst = ProviderStatus()

if __name__ == '__main__':
    unittest.main()
