# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.route_aggregation_rules_change_type import RouteAggregationRulesChangeType

class TestRouteAggregationRulesChangeType(unittest.TestCase):
    """RouteAggregationRulesChangeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRouteAggregationRulesChangeType(self):
        """Test RouteAggregationRulesChangeType"""
        # inst = RouteAggregationRulesChangeType()

if __name__ == '__main__':
    unittest.main()
