# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.cloud_router_action_state import CloudRouterActionState

class TestCloudRouterActionState(unittest.TestCase):
    """CloudRouterActionState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudRouterActionState(self):
        """Test CloudRouterActionState"""
        # inst = CloudRouterActionState()

if __name__ == '__main__':
    unittest.main()
