# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.port_order_purchase_order_selection_type import PortOrderPurchaseOrderSelectionType

class TestPortOrderPurchaseOrderSelectionType(unittest.TestCase):
    """PortOrderPurchaseOrderSelectionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortOrderPurchaseOrderSelectionType(self):
        """Test PortOrderPurchaseOrderSelectionType"""
        # inst = PortOrderPurchaseOrderSelectionType()

if __name__ == '__main__':
    unittest.main()
