# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.cloud_router_sort_direction import CloudRouterSortDirection

class TestCloudRouterSortDirection(unittest.TestCase):
    """CloudRouterSortDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudRouterSortDirection(self):
        """Test CloudRouterSortDirection"""
        # inst = CloudRouterSortDirection()

if __name__ == '__main__':
    unittest.main()
