# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.sort_by import SortBy

class TestSortBy(unittest.TestCase):
    """SortBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortBy(self):
        """Test SortBy"""
        # inst = SortBy()

if __name__ == '__main__':
    unittest.main()
