# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.port_type import PortType

class TestPortType(unittest.TestCase):
    """PortType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortType(self):
        """Test PortType"""
        # inst = PortType()

if __name__ == '__main__':
    unittest.main()
