# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.interface_type import InterfaceType

class TestInterfaceType(unittest.TestCase):
    """InterfaceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInterfaceType(self):
        """Test InterfaceType"""
        # inst = InterfaceType()

if __name__ == '__main__':
    unittest.main()
