# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.network_sort_by_response import NetworkSortByResponse

class TestNetworkSortByResponse(unittest.TestCase):
    """NetworkSortByResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkSortByResponse(self):
        """Test NetworkSortByResponse"""
        # inst = NetworkSortByResponse()

if __name__ == '__main__':
    unittest.main()
