# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.network_equinix_status import NetworkEquinixStatus

class TestNetworkEquinixStatus(unittest.TestCase):
    """NetworkEquinixStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkEquinixStatus(self):
        """Test NetworkEquinixStatus"""
        # inst = NetworkEquinixStatus()

if __name__ == '__main__':
    unittest.main()
