# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.network_sort_direction import NetworkSortDirection

class TestNetworkSortDirection(unittest.TestCase):
    """NetworkSortDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkSortDirection(self):
        """Test NetworkSortDirection"""
        # inst = NetworkSortDirection()

if __name__ == '__main__':
    unittest.main()
