# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.stream_subscription_type import StreamSubscriptionType

class TestStreamSubscriptionType(unittest.TestCase):
    """StreamSubscriptionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamSubscriptionType(self):
        """Test StreamSubscriptionType"""
        # inst = StreamSubscriptionType()

if __name__ == '__main__':
    unittest.main()
