# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.port_service_type import PortServiceType

class TestPortServiceType(unittest.TestCase):
    """PortServiceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPortServiceType(self):
        """Test PortServiceType"""
        # inst = PortServiceType()

if __name__ == '__main__':
    unittest.main()
