# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.fabric_cloud_router_code import FabricCloudRouterCode

class TestFabricCloudRouterCode(unittest.TestCase):
    """FabricCloudRouterCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFabricCloudRouterCode(self):
        """Test FabricCloudRouterCode"""
        # inst = FabricCloudRouterCode()

if __name__ == '__main__':
    unittest.main()
