# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.virtual_connection_price_access_point_type import VirtualConnectionPriceAccessPointType

class TestVirtualConnectionPriceAccessPointType(unittest.TestCase):
    """VirtualConnectionPriceAccessPointType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVirtualConnectionPriceAccessPointType(self):
        """Test VirtualConnectionPriceAccessPointType"""
        # inst = VirtualConnectionPriceAccessPointType()

if __name__ == '__main__':
    unittest.main()
