# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.simplified_token_network_type import SimplifiedTokenNetworkType

class TestSimplifiedTokenNetworkType(unittest.TestCase):
    """SimplifiedTokenNetworkType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimplifiedTokenNetworkType(self):
        """Test SimplifiedTokenNetworkType"""
        # inst = SimplifiedTokenNetworkType()

if __name__ == '__main__':
    unittest.main()
