# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""

import unittest

from equinix.services.fabricv4.models.price_charge_type import PriceChargeType

class TestPriceChargeType(unittest.TestCase):
    """PriceChargeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceChargeType(self):
        """Test PriceChargeType"""
        # inst = PriceChargeType()

if __name__ == '__main__':
    unittest.main()
