# coding: utf-8

"""
    Metal API

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.metalv1.models.capacity_list1 import CapacityList1

class TestCapacityList1(unittest.TestCase):
    """CapacityList1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CapacityList1:
        """Test CapacityList1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CapacityList1`
        """
        model = CapacityList1()
        if include_optional:
            return CapacityList1(
                capacity = {
                    'key' : {
                        'key' : equinix.services.metalv1.models.capacity_level_per_baremetal.CapacityLevelPerBaremetal(
                            href = '', 
                            level = '', )
                        }
                    },
                href = ''
            )
        else:
            return CapacityList1(
        )
        """

    def testCapacityList1(self):
        """Test CapacityList1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
