# coding: utf-8

"""
    Metal API

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.metalv1.api.roles_api import RolesApi


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RolesApi()

    def tearDown(self) -> None:
        pass

    def test_get_organization_role(self) -> None:
        """Test case for get_organization_role

        Get details about a specific role
        """
        pass

    def test_list_organization_roles(self) -> None:
        """Test case for list_organization_roles

        List available roles
        """
        pass


if __name__ == '__main__':
    unittest.main()
