# coding: utf-8

"""
    Metal API

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from equinix.services.metalv1.models.member import Member

class TestMember(unittest.TestCase):
    """Member unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Member:
        """Test Member
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Member`
        """
        model = Member()
        if include_optional:
            return Member(
                bound_roles = ["permrv2-:id"],
                href = '',
                id = '',
                organization = equinix.services.metalv1.models.href.Href(
                    href = '', ),
                projects = [
                    equinix.services.metalv1.models.href.Href(
                        href = '', )
                    ],
                projects_count = 56,
                roles = [
                    'admin'
                    ],
                user = equinix.services.metalv1.models.href.Href(
                    href = '', )
            )
        else:
            return Member(
        )
        """

    def testMember(self):
        """Test Member"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
