# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Account(BaseModel):
    """
    Account
    """ # noqa: E501
    account_id: Optional[StrictInt] = Field(default=None, description="Account identifier", alias="accountId")
    account_number: Optional[StrictInt] = Field(default=None, description="Account number", alias="accountNumber")
    account_name: Optional[StrictStr] = Field(default=None, description="Account name", alias="accountName")
    ucm_id: Optional[StrictStr] = Field(default=None, description="Account ucm id", alias="ucmId")
    global_cust_id: Optional[StrictStr] = Field(default=None, description="Global customer organization id", alias="globalCustId")
    org_id: Optional[StrictInt] = Field(default=None, description="Customer organization id", alias="orgId")
    organization_name: Optional[StrictStr] = Field(default=None, description="Customer organization name", alias="organizationName")
    sub_customes: Optional[List[Account]] = Field(default=None, description="All sub customer accounts", alias="subCustomes")
    country_code: Optional[StrictStr] = Field(default=None, description="Account country code", alias="countryCode")
    operational_unit: Optional[StrictStr] = Field(default=None, description="Account operational unit", alias="operationalUnit")
    operational_unit_metros: Optional[List[StrictStr]] = Field(default=None, description="Account operational unit metros", alias="operationalUnitMetros")
    signature_required: Optional[StrictBool] = Field(default=None, description="Is signature required", alias="signatureRequired")
    po_bearing: Optional[StrictBool] = Field(default=None, description="Purchase order bearing", alias="poBearing")
    default: Optional[StrictBool] = Field(default=None, description="Default account or not")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["accountId", "accountNumber", "accountName", "ucmId", "globalCustId", "orgId", "organizationName", "subCustomes", "countryCode", "operationalUnit", "operationalUnitMetros", "signatureRequired", "poBearing", "default"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Account from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sub_customes (list)
        _items = []
        if self.sub_customes:
            for _item_sub_customes in self.sub_customes:
                if _item_sub_customes:
                    _items.append(_item_sub_customes.to_dict())
            _dict['subCustomes'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Account from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountId": obj.get("accountId"),
            "accountNumber": obj.get("accountNumber"),
            "accountName": obj.get("accountName"),
            "ucmId": obj.get("ucmId"),
            "globalCustId": obj.get("globalCustId"),
            "orgId": obj.get("orgId"),
            "organizationName": obj.get("organizationName"),
            "subCustomes": [Account.from_dict(_item) for _item in obj["subCustomes"]] if obj.get("subCustomes") is not None else None,
            "countryCode": obj.get("countryCode"),
            "operationalUnit": obj.get("operationalUnit"),
            "operationalUnitMetros": obj.get("operationalUnitMetros"),
            "signatureRequired": obj.get("signatureRequired"),
            "poBearing": obj.get("poBearing"),
            "default": obj.get("default")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

# TODO: Rewrite to not use raise_errors
Account.model_rebuild(raise_errors=False)

