# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AppDomainState(str, Enum):
    """
    App Domain lifecycle state
    """

    """
    allowed enum values
    """
    PENDING_VERIFICATION = 'PENDING_VERIFICATION'
    PROVISIONING_FAILED = 'PROVISIONING_FAILED'
    PROVISIONED = 'PROVISIONED'
    DEPROVISIONING = 'DEPROVISIONING'
    DEPROVISIONING_FAILED = 'DEPROVISIONING_FAILED'
    DEPROVISIONED = 'DEPROVISIONED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AppDomainState from a JSON string"""
        return cls(json.loads(json_str))


