# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CompanyProfileSearchFieldName(str, Enum):
    """
    Searchable field names in company profile
    """

    """
    allowed enum values
    """
    SLASH_NAME = '/name'
    SLASH_UUID = '/uuid'
    SLASH_TAGS_SLASH_NAME = '/tags/name'
    SLASH_TAGS_SLASH_UUID = '/tags/uuid'
    SLASH_TAGS_SLASH_DISPLAY_NAME = '/tags/displayName'
    SLASH_STATE = '/state'
    SLASH_METROS_SLASH_METRO_CODE = '/metros/metroCode'
    SLASH_CHANGE_SLASH_STATUS = '/change/status'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CompanyProfileSearchFieldName from a JSON string"""
        return cls(json.loads(json_str))


