# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from equinix.services.fabricv4.models.company_profile_search_field_name import CompanyProfileSearchFieldName
from equinix.services.fabricv4.models.operator_enum import OperatorEnum
from typing import Optional, Set
from typing_extensions import Self

class CompanyProfileSearchSimpleExpression(BaseModel):
    """
    CompanyProfileSearchSimpleExpression
    """ # noqa: E501
    var_property: CompanyProfileSearchFieldName = Field(description="Searchable field name. Properties are grouped by their supported operators: String properties (support all operators):  * `/name` - Company profile name  * `/uuid` - Company profile UUID  * `/tags/name` - Tag name  * `/tags/uuid` - Tag UUID  * `/tags/displayName` - Tag display name  Discrete value properties (only support `=`, `!=`, `IN`, `NOT IN`):  * `/state` - Company profile state (`PENDING`, `PROVISIONED`, `DEPROVISIONED`, `REJECTED`)  * `/metros/metroCode` - Metro code (e.g. `SV`, `NY`, `DC`)  * `/change/status` - Change status (`PENDING`, `COMPLETED`, `REJECTED`) — seller and admin users only ", alias="property")
    operator: OperatorEnum = Field(description="Comparison operator. `LIKE`, `NOT LIKE`, `ILIKE`, and `NOT ILIKE` require exactly one value. All other operators accept one or more values.  * `=` - equal; equivalent to `IN` when multiple values are provided  * `!=` - not equal; equivalent to `NOT IN` when multiple values are provided  * `LIKE` - case-sensitive partial match (single value)  * `NOT LIKE` - case-sensitive partial non-match (single value)  * `ILIKE` - case-insensitive partial match (single value)  * `NOT ILIKE` - case-insensitive partial non-match (single value)  * `IN` - matches any of the provided values  * `NOT IN` - does not match any of the provided values ")
    values: Annotated[List[StrictStr], Field(min_length=1)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["property", "operator", "values"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompanyProfileSearchSimpleExpression from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompanyProfileSearchSimpleExpression from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "property": obj.get("property"),
            "operator": obj.get("operator"),
            "values": obj.get("values")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


