# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExchangeServiceResponseState(str, Enum):
    """
    State
    """

    """
    allowed enum values
    """
    PROVISIONING = 'PROVISIONING'
    PROVISIONING_FAILED = 'PROVISIONING_FAILED'
    PENDING_ACTIVATION = 'PENDING_ACTIVATION'
    ACTIVATING = 'ACTIVATING'
    ACTIVATING_FAILED = 'ACTIVATING_FAILED'
    PROVISIONED = 'PROVISIONED'
    REPROVISIONING = 'REPROVISIONING'
    REPROVISIONING_FAILED = 'REPROVISIONING_FAILED'
    DEPROVISIONING = 'DEPROVISIONING'
    DEPROVISIONED = 'DEPROVISIONED'
    DEPROVISIONING_FAILED = 'DEPROVISIONING_FAILED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExchangeServiceResponseState from a JSON string"""
        return cls(json.loads(json_str))


