# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from equinix.services.fabricv4.models.exchange_service_notification import ExchangeServiceNotification
from equinix.services.fabricv4.models.exchange_service_response_state import ExchangeServiceResponseState
from equinix.services.fabricv4.models.exchange_service_response_type import ExchangeServiceResponseType
from equinix.services.fabricv4.models.order import Order
from equinix.services.fabricv4.models.platform_changelog import PlatformChangelog
from equinix.services.fabricv4.models.project import Project
from equinix.services.fabricv4.models.public_peering_connection_response import PublicPeeringConnectionResponse
from equinix.services.fabricv4.models.routing_protocol_response import RoutingProtocolResponse
from equinix.services.fabricv4.models.simplified_account import SimplifiedAccount
from equinix.services.fabricv4.models.simplified_location import SimplifiedLocation
from typing import Optional, Set
from typing_extensions import Self

class ExchangeServiceResponse(BaseModel):
    """
    ExchangeServiceResponse
    """ # noqa: E501
    href: Optional[StrictStr] = Field(default=None, description="Internet Exchange Service URI")
    uuid: Optional[StrictStr] = Field(default=None, description="Internet Exchange Service identifier")
    type: Optional[ExchangeServiceResponseType] = ExchangeServiceResponseType.IX
    name: Optional[StrictStr] = Field(default=None, description="Name")
    bandwidth: Optional[StrictInt] = Field(default=None, description="bandwidth in Mbps")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    state: Optional[ExchangeServiceResponseState] = None
    location: Optional[SimplifiedLocation] = None
    public_peering_connection: Optional[PublicPeeringConnectionResponse] = Field(default=None, alias="publicPeeringConnection")
    routing_protocol: Optional[RoutingProtocolResponse] = Field(default=None, alias="routingProtocol")
    order: Optional[Order] = None
    project: Optional[Project] = None
    account: Optional[SimplifiedAccount] = None
    notifications: Optional[List[ExchangeServiceNotification]] = Field(default=None, description="Preferences for notifications on Internet Exchange Service configuration or status changes")
    changelog: Optional[PlatformChangelog] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["href", "uuid", "type", "name", "bandwidth", "description", "state", "location", "publicPeeringConnection", "routingProtocol", "order", "project", "account", "notifications", "changelog"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExchangeServiceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of public_peering_connection
        if self.public_peering_connection:
            _dict['publicPeeringConnection'] = self.public_peering_connection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of routing_protocol
        if self.routing_protocol:
            _dict['routingProtocol'] = self.routing_protocol.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['project'] = self.project.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notifications (list)
        _items = []
        if self.notifications:
            for _item_notifications in self.notifications:
                if _item_notifications:
                    _items.append(_item_notifications.to_dict())
            _dict['notifications'] = _items
        # override the default output from pydantic by calling `to_dict()` of changelog
        if self.changelog:
            _dict['changelog'] = self.changelog.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExchangeServiceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "href": obj.get("href"),
            "uuid": obj.get("uuid"),
            "type": obj.get("type") if obj.get("type") is not None else ExchangeServiceResponseType.IX,
            "name": obj.get("name"),
            "bandwidth": obj.get("bandwidth"),
            "description": obj.get("description"),
            "state": obj.get("state"),
            "location": SimplifiedLocation.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "publicPeeringConnection": PublicPeeringConnectionResponse.from_dict(obj["publicPeeringConnection"]) if obj.get("publicPeeringConnection") is not None else None,
            "routingProtocol": RoutingProtocolResponse.from_dict(obj["routingProtocol"]) if obj.get("routingProtocol") is not None else None,
            "order": Order.from_dict(obj["order"]) if obj.get("order") is not None else None,
            "project": Project.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "account": SimplifiedAccount.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "notifications": [ExchangeServiceNotification.from_dict(_item) for _item in obj["notifications"]] if obj.get("notifications") is not None else None,
            "changelog": PlatformChangelog.from_dict(obj["changelog"]) if obj.get("changelog") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


