# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GatewayType(str, Enum):
    """
    Gateway type
    """

    """
    allowed enum values
    """
    VPN_GW = 'VPN_GW'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GatewayType from a JSON string"""
        return cls(json.loads(json_str))


