# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InterconnectSearchFieldName(str, Enum):
    """
    Possible field names to use on filters
    """

    """
    allowed enum values
    """
    SLASH_UUID = '/uuid'
    SLASH_TYPE = '/type'
    SLASH_NAME = '/name'
    SLASH_STATE = '/state'
    SLASH_DESCRIPTION = '/description'
    SLASH_LOCATION_SLASH_METRO_CODE = '/location/metroCode'
    SLASH_PACKAGE_SLASH_CODE = '/package/code'
    SLASH_PROJECT_SLASH_PROJECT_ID = '/project/projectId'
    SLASH_CHANGE_LOG_SLASH_CREATED_DATE_TIME = '/changeLog/createdDateTime'
    SLASH_CHANGE_LOG_SLASH_UPDATED_DATE_TIME = '/changeLog/updatedDateTime'
    SLASH_CHANGE_LOG_SLASH_DELETED_DATE_TIME = '/changeLog/deletedDateTime'
    SLASH_ROUTER_SLASH_UUID = '/router/uuid'
    SLASH_STAR = '/*'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InterconnectSearchFieldName from a JSON string"""
        return cls(json.loads(json_str))


