# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from equinix.services.fabricv4.models.internet_access_connection_static_request import InternetAccessConnectionStaticRequest
from equinix.services.fabricv4.models.internet_access_customer_route_request import InternetAccessCustomerRouteRequest
from equinix.services.fabricv4.models.internet_access_routing_protocol_request import InternetAccessRoutingProtocolRequest
from equinix.services.fabricv4.models.internet_access_routing_protocol_type import InternetAccessRoutingProtocolType
from typing import Optional, Set
from typing_extensions import Self

class InternetAccessRoutingProtocolStaticRequest(InternetAccessRoutingProtocolRequest):
    """
    InternetAccessRoutingProtocolStaticRequest
    """ # noqa: E501
    connections: Annotated[List[InternetAccessConnectionStaticRequest], Field(min_length=1, max_length=2)]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "customerRoutes", "connections"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternetAccessRoutingProtocolStaticRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in customer_routes (list)
        _items = []
        if self.customer_routes:
            for _item_customer_routes in self.customer_routes:
                if _item_customer_routes:
                    _items.append(_item_customer_routes.to_dict())
            _dict['customerRoutes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in connections (list)
        _items = []
        if self.connections:
            for _item_connections in self.connections:
                if _item_connections:
                    _items.append(_item_connections.to_dict())
            _dict['connections'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternetAccessRoutingProtocolStaticRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "customerRoutes": [InternetAccessCustomerRouteRequest.from_dict(_item) for _item in obj["customerRoutes"]] if obj.get("customerRoutes") is not None else None,
            "connections": [InternetAccessConnectionStaticRequest.from_dict(_item) for _item in obj["connections"]] if obj.get("connections") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


