# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LoaFieldName(str, Enum):
    """
    Possible field names to use on filters
    """

    """
    allowed enum values
    """
    SLASH_UUID = '/uuid'
    SLASH_STATE = '/state'
    SLASH_TYPE = '/type'
    SLASH_NAME = '/name'
    SLASH_AUTHORIZED_PRODUCT_TYPE = '/authorizedProductType'
    SLASH_EXPIRATION_DATE_TIME = '/expirationDateTime'
    SLASH_REQUESTOR_SLASH_EMAIL = '/requestor/email'
    SLASH_REQUESTOR_SLASH_ORG_ID = '/requestor/orgId'
    SLASH_REQUESTOR_SLASH_ORG_NAME = '/requestor/orgName'
    SLASH_ISSUER_SLASH_EMAIL = '/issuer/email'
    SLASH_ISSUER_SLASH_ORG_ID = '/issuer/orgId'
    SLASH_ISSUER_SLASH_ORG_NAME = '/issuer/orgName'
    SLASH_DEMARCATION_POINT_SLASH_PATCH_PANEL_ID = '/demarcationPoint/patchPanelId'
    SLASH_DEMARCATION_POINT_SLASH_PATCH_PANEL_PORT_A = '/demarcationPoint/patchPanelPortA'
    SLASH_DEMARCATION_POINT_SLASH_PATCH_PANEL_PORT_B = '/demarcationPoint/patchPanelPortB'
    SLASH_DEMARCATION_POINT_SLASH_CONNECTOR_TYPE = '/demarcationPoint/connectorType'
    SLASH_DEMARCATION_POINT_SLASH_CAGE_UNIQUE_SPACE_ID = '/demarcationPoint/cageUniqueSpaceId'
    SLASH_LOCATION_SLASH_IBX_CODE = '/location/ibxCode'
    SLASH_CHANGE_LOG_SLASH_CREATED_DATE_TIME = '/changeLog/createdDateTime'
    SLASH_CHANGE_LOG_SLASH_UPDATED_DATE_TIME = '/changeLog/updatedDateTime'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoaFieldName from a JSON string"""
        return cls(json.loads(json_str))


