# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LoaNoteDetailsType(str, Enum):
    """
    Indicates which party added the note. <br> ISSUER — note was added by a user from the issuer organization. <br> REQUESTOR — note was added by a user from the requestor organization. 
    """

    """
    allowed enum values
    """
    ISSUER = 'ISSUER'
    REQUESTOR = 'REQUESTOR'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoaNoteDetailsType from a JSON string"""
        return cls(json.loads(json_str))


