# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LoaActionType(str, Enum):
    """
    Action to perform on the LOA.
    """

    """
    allowed enum values
    """
    LOA_ISSUER_AUTHORIZATION = 'LOA_ISSUER_AUTHORIZATION'
    LOA_REQUESTOR_ACCEPTANCE = 'LOA_REQUESTOR_ACCEPTANCE'
    LOA_COPY_LINK = 'LOA_COPY_LINK'
    LOA_SEND_EMAIL_NOTIFICATION = 'LOA_SEND_EMAIL_NOTIFICATION'
    LOA_CANCEL = 'LOA_CANCEL'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoaActionType from a JSON string"""
        return cls(json.loads(json_str))


