# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LoaActionType(str, Enum):
    """
    Loa Action Type
    """

    """
    allowed enum values
    """
    AUTHORIZE_LOA = 'AUTHORIZE_LOA'
    ACCEPT_LOA = 'ACCEPT_LOA'
    COPY_LOA = 'COPY_LOA'
    SEND_LOA = 'SEND_LOA'
    CANCEL_LOA = 'CANCEL_LOA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoaActionType from a JSON string"""
        return cls(json.loads(json_str))


