# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OperatorEnum(str, Enum):
    """
    Comparison operators for filtering
    """

    """
    allowed enum values
    """
    EQUAL = '='
    EXCLAMATION_EQUAL = '!='
    LIKE = 'LIKE'
    NOT_LIKE = 'NOT LIKE'
    ILIKE = 'ILIKE'
    NOT_ILIKE = 'NOT ILIKE'
    IN = 'IN'
    NOT_IN = 'NOT IN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OperatorEnum from a JSON string"""
        return cls(json.loads(json_str))


