# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from equinix.services.fabricv4.models.changelog import Changelog
from equinix.services.fabricv4.models.optical_connect_a_side_response import OpticalConnectASideResponse
from equinix.services.fabricv4.models.optical_connect_notification import OpticalConnectNotification
from equinix.services.fabricv4.models.optical_connect_order import OpticalConnectOrder
from equinix.services.fabricv4.models.optical_connect_redundancy import OpticalConnectRedundancy
from equinix.services.fabricv4.models.optical_connect_response_bmmr_type import OpticalConnectResponseBmmrType
from equinix.services.fabricv4.models.optical_connect_response_connection_destination_type import OpticalConnectResponseConnectionDestinationType
from equinix.services.fabricv4.models.optical_connect_response_path_type import OpticalConnectResponsePathType
from equinix.services.fabricv4.models.optical_connect_response_type import OpticalConnectResponseType
from equinix.services.fabricv4.models.optical_connect_state import OpticalConnectState
from equinix.services.fabricv4.models.optical_connect_z_side_response import OpticalConnectZSideResponse
from equinix.services.fabricv4.models.simplified_account import SimplifiedAccount
from typing import Optional, Set
from typing_extensions import Self

class OpticalConnectResponse(BaseModel):
    """
    Optical Metro Connect connection with its current state and the resolved         physical termination points at both ends.
    """ # noqa: E501
    href: Optional[StrictStr] = Field(default=None, description="URI of this Optical Connect resource.")
    uuid: Optional[StrictStr] = Field(default=None, description="Unique identifier of this Optical Connect.")
    type: Optional[OpticalConnectResponseType] = None
    name: Optional[StrictStr] = Field(default=None, description="Equinix-assigned name, derived from the account number and the two IBX locations. ")
    state: Optional[OpticalConnectState] = None
    bandwidth: Optional[StrictInt] = Field(default=None, description="Provisioned connection bandwidth in Mbps.")
    connection_destination_type: Optional[OpticalConnectResponseConnectionDestinationType] = Field(default=None, alias="connectionDestinationType")
    path_type: Optional[OpticalConnectResponsePathType] = Field(default=None, alias="pathType")
    bmmr_type: Optional[OpticalConnectResponseBmmrType] = Field(default=None, alias="bmmrType")
    redundancy: Optional[OpticalConnectRedundancy] = None
    a_side: Optional[OpticalConnectASideResponse] = Field(default=None, alias="aSide")
    z_side: Optional[OpticalConnectZSideResponse] = Field(default=None, alias="zSide")
    order: Optional[OpticalConnectOrder] = None
    account: Optional[SimplifiedAccount] = None
    notifications: Optional[List[OpticalConnectNotification]] = Field(default=None, description="Preferences for notifications on connection configuration or status changes")
    change_log: Optional[Changelog] = Field(default=None, alias="changeLog")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["href", "uuid", "type", "name", "state", "bandwidth", "connectionDestinationType", "pathType", "bmmrType", "redundancy", "aSide", "zSide", "order", "account", "notifications", "changeLog"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpticalConnectResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "href",
            "uuid",
            "name",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of redundancy
        if self.redundancy:
            _dict['redundancy'] = self.redundancy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of a_side
        if self.a_side:
            _dict['aSide'] = self.a_side.to_dict()
        # override the default output from pydantic by calling `to_dict()` of z_side
        if self.z_side:
            _dict['zSide'] = self.z_side.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notifications (list)
        _items = []
        if self.notifications:
            for _item_notifications in self.notifications:
                if _item_notifications:
                    _items.append(_item_notifications.to_dict())
            _dict['notifications'] = _items
        # override the default output from pydantic by calling `to_dict()` of change_log
        if self.change_log:
            _dict['changeLog'] = self.change_log.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpticalConnectResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "href": obj.get("href"),
            "uuid": obj.get("uuid"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "state": obj.get("state"),
            "bandwidth": obj.get("bandwidth"),
            "connectionDestinationType": obj.get("connectionDestinationType"),
            "pathType": obj.get("pathType"),
            "bmmrType": obj.get("bmmrType"),
            "redundancy": OpticalConnectRedundancy.from_dict(obj["redundancy"]) if obj.get("redundancy") is not None else None,
            "aSide": OpticalConnectASideResponse.from_dict(obj["aSide"]) if obj.get("aSide") is not None else None,
            "zSide": OpticalConnectZSideResponse.from_dict(obj["zSide"]) if obj.get("zSide") is not None else None,
            "order": OpticalConnectOrder.from_dict(obj["order"]) if obj.get("order") is not None else None,
            "account": SimplifiedAccount.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "notifications": [OpticalConnectNotification.from_dict(_item) for _item in obj["notifications"]] if obj.get("notifications") is not None else None,
            "changeLog": Changelog.from_dict(obj["changeLog"]) if obj.get("changeLog") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


