# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OpticalConnectResponseBmmrType(str, Enum):
    """
    BMMR infrastructure ownership type. <br> EQUINIX - Equinix-operated. <br> SELF - customer-operated. <br> Required only when connectionDestinationType is BMMR. 
    """

    """
    allowed enum values
    """
    EQUINIX = 'EQUINIX'
    SELF = 'SELF'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OpticalConnectResponseBmmrType from a JSON string"""
        return cls(json.loads(json_str))


