# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from equinix.services.fabricv4.models.optical_connect_a_side_request import OpticalConnectASideRequest
from equinix.services.fabricv4.models.optical_connect_notification import OpticalConnectNotification
from equinix.services.fabricv4.models.optical_connect_order import OpticalConnectOrder
from equinix.services.fabricv4.models.optical_connect_post_request_bmmr_type import OpticalConnectPostRequestBmmrType
from equinix.services.fabricv4.models.optical_connect_post_request_connection_destination_type import OpticalConnectPostRequestConnectionDestinationType
from equinix.services.fabricv4.models.optical_connect_post_request_path_type import OpticalConnectPostRequestPathType
from equinix.services.fabricv4.models.optical_connect_post_request_type import OpticalConnectPostRequestType
from equinix.services.fabricv4.models.optical_connect_redundancy import OpticalConnectRedundancy
from equinix.services.fabricv4.models.optical_connect_z_side_request import OpticalConnectZSideRequest
from equinix.services.fabricv4.models.simplified_account import SimplifiedAccount
from typing import Optional, Set
from typing_extensions import Self

class OpticalConnectPostRequest(BaseModel):
    """
    Request to order a single connection. The A-side is always a patch panel         port in your own cage; the Z-side shape depends on         connectionDestinationType.
    """ # noqa: E501
    type: OpticalConnectPostRequestType
    bandwidth: StrictInt = Field(description="Connection bandwidth Mbps. <br> Available bandwidths depend on the IBX pair. <br> 1000 - 1 Gbps. <br> 10000 - 10 Gbps. <br> 100000 - 100 Gbps. <br> ")
    connection_destination_type: OpticalConnectPostRequestConnectionDestinationType = Field(alias="connectionDestinationType")
    path_type: OpticalConnectPostRequestPathType = Field(alias="pathType")
    redundancy: Optional[OpticalConnectRedundancy] = None
    a_side: OpticalConnectASideRequest = Field(alias="aSide")
    z_side: OpticalConnectZSideRequest = Field(alias="zSide")
    order: Optional[OpticalConnectOrder] = None
    account: Optional[SimplifiedAccount] = None
    notifications: Optional[List[OpticalConnectNotification]] = Field(default=None, description="Contacts to notify about connection configuration and status changes")
    bmmr_type: Optional[OpticalConnectPostRequestBmmrType] = Field(default=None, alias="bmmrType")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "bandwidth", "connectionDestinationType", "pathType", "redundancy", "aSide", "zSide", "order", "account", "notifications", "bmmrType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpticalConnectPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of redundancy
        if self.redundancy:
            _dict['redundancy'] = self.redundancy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of a_side
        if self.a_side:
            _dict['aSide'] = self.a_side.to_dict()
        # override the default output from pydantic by calling `to_dict()` of z_side
        if self.z_side:
            _dict['zSide'] = self.z_side.to_dict()
        # override the default output from pydantic by calling `to_dict()` of order
        if self.order:
            _dict['order'] = self.order.to_dict()
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in notifications (list)
        _items = []
        if self.notifications:
            for _item_notifications in self.notifications:
                if _item_notifications:
                    _items.append(_item_notifications.to_dict())
            _dict['notifications'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpticalConnectPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "bandwidth": obj.get("bandwidth"),
            "connectionDestinationType": obj.get("connectionDestinationType"),
            "pathType": obj.get("pathType"),
            "redundancy": OpticalConnectRedundancy.from_dict(obj["redundancy"]) if obj.get("redundancy") is not None else None,
            "aSide": OpticalConnectASideRequest.from_dict(obj["aSide"]) if obj.get("aSide") is not None else None,
            "zSide": OpticalConnectZSideRequest.from_dict(obj["zSide"]) if obj.get("zSide") is not None else None,
            "order": OpticalConnectOrder.from_dict(obj["order"]) if obj.get("order") is not None else None,
            "account": SimplifiedAccount.from_dict(obj["account"]) if obj.get("account") is not None else None,
            "notifications": [OpticalConnectNotification.from_dict(_item) for _item in obj["notifications"]] if obj.get("notifications") is not None else None,
            "bmmrType": obj.get("bmmrType")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


