# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OpticalConnectState(str, Enum):
    """
    Optical Connect lifecycle states.
    """

    """
    allowed enum values
    """
    PROVISIONING = 'PROVISIONING'
    PROVISIONED = 'PROVISIONED'
    PROVISIONING_FAILED = 'PROVISIONING_FAILED'
    REPROVISIONING = 'REPROVISIONING'
    REPROVISIONING_FAILED = 'REPROVISIONING_FAILED'
    DEPROVISIONING = 'DEPROVISIONING'
    DEPROVISIONED = 'DEPROVISIONED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OpticalConnectState from a JSON string"""
        return cls(json.loads(json_str))


