# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RfAttachmentSortItemProperty(str, Enum):
    """
    Possible field names to use on sorting
    """

    """
    allowed enum values
    """
    SLASH_TYPE = '/type'
    SLASH_UUID = '/uuid'
    SLASH_DIRECTION = '/direction'
    SLASH_ATTACHMENT_STATUS = '/attachmentStatus'
    SLASH_CHANGE_LOG_SLASH_CREATED_DATE_TIME = '/changeLog/createdDateTime'
    SLASH_CHANGE_LOG_SLASH_UPDATED_DATE_TIME = '/changeLog/updatedDateTime'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RfAttachmentSortItemProperty from a JSON string"""
        return cls(json.loads(json_str))


