# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from equinix.services.fabricv4.models.route_filter_rule_simple_expression import RouteFilterRuleSimpleExpression
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

ROUTEFILTERRULEEXPRESSION_ANY_OF_SCHEMAS = ["RouteFilterRuleAndExpression", "RouteFilterRuleOrExpression", "RouteFilterRuleSimpleExpression"]

class RouteFilterRuleExpression(BaseModel):
    """
    Filter expression that can be AND, OR, or a simple expression
    """

    # data type: RouteFilterRuleAndExpression
    anyof_schema_1_validator: Optional[RouteFilterRuleAndExpression] = None
    # data type: RouteFilterRuleOrExpression
    anyof_schema_2_validator: Optional[RouteFilterRuleOrExpression] = None
    # data type: RouteFilterRuleSimpleExpression
    anyof_schema_3_validator: Optional[RouteFilterRuleSimpleExpression] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[RouteFilterRuleAndExpression, RouteFilterRuleOrExpression, RouteFilterRuleSimpleExpression]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "RouteFilterRuleAndExpression", "RouteFilterRuleOrExpression", "RouteFilterRuleSimpleExpression" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = RouteFilterRuleExpression.model_construct()
        error_messages = []
        # validate data type: RouteFilterRuleAndExpression
        if not isinstance(v, RouteFilterRuleAndExpression):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RouteFilterRuleAndExpression`")
        else:
            return v

        # validate data type: RouteFilterRuleOrExpression
        if not isinstance(v, RouteFilterRuleOrExpression):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RouteFilterRuleOrExpression`")
        else:
            return v

        # validate data type: RouteFilterRuleSimpleExpression
        if not isinstance(v, RouteFilterRuleSimpleExpression):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RouteFilterRuleSimpleExpression`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in RouteFilterRuleExpression with anyOf schemas: RouteFilterRuleAndExpression, RouteFilterRuleOrExpression, RouteFilterRuleSimpleExpression. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[RouteFilterRuleAndExpression] = None
        try:
            instance.actual_instance = RouteFilterRuleAndExpression.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[RouteFilterRuleOrExpression] = None
        try:
            instance.actual_instance = RouteFilterRuleOrExpression.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[RouteFilterRuleSimpleExpression] = None
        try:
            instance.actual_instance = RouteFilterRuleSimpleExpression.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into RouteFilterRuleExpression with anyOf schemas: RouteFilterRuleAndExpression, RouteFilterRuleOrExpression, RouteFilterRuleSimpleExpression. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], RouteFilterRuleAndExpression, RouteFilterRuleOrExpression, RouteFilterRuleSimpleExpression]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())

from equinix.services.fabricv4.models.route_filter_rule_and_expression import RouteFilterRuleAndExpression
from equinix.services.fabricv4.models.route_filter_rule_or_expression import RouteFilterRuleOrExpression
# TODO: Rewrite to not use raise_errors
RouteFilterRuleExpression.model_rebuild(raise_errors=False)

