# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ServiceTokenSearchExpressionOperator(str, Enum):
    """
    ServiceTokenSearchExpressionOperator
    """

    """
    allowed enum values
    """
    EQUAL = '='
    EXCLAMATION_EQUAL = '!='
    LIKE = 'LIKE'
    ILIKE = 'ILIKE'
    LESS_THAN = '<'
    GREATER_THAN = '>'
    LESS_THAN_EQUAL = '<='
    GREATER_THAN_EQUAL = '>='
    IN = 'IN'
    NOT_IN = 'NOT IN'
    BETWEEN = 'BETWEEN'
    NOT_BETWEEN = 'NOT BETWEEN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ServiceTokenSearchExpressionOperator from a JSON string"""
        return cls(json.loads(json_str))


