# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from equinix.services.fabricv4.models.service_profile_last_mile_delivery_date_range import ServiceProfileLastMileDeliveryDateRange
from equinix.services.fabricv4.models.service_profile_last_mile_offering import ServiceProfileLastMileOffering
from typing import Optional, Set
from typing_extensions import Self

class ServiceProfileLastMileProductCatalog(BaseModel):
    """
    Last-mile provider catalog details.
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Last-mile provider or catalog name.")
    web_url: Optional[StrictStr] = Field(default=None, description="Last-mile catalog or provider website URL.", alias="webUrl")
    delivery_date: Optional[ServiceProfileLastMileDeliveryDateRange] = Field(default=None, alias="deliveryDate")
    offerings: Optional[List[ServiceProfileLastMileOffering]] = Field(default=None, description="Available last-mile offerings.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "webUrl", "deliveryDate", "offerings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceProfileLastMileProductCatalog from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delivery_date
        if self.delivery_date:
            _dict['deliveryDate'] = self.delivery_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in offerings (list)
        _items = []
        if self.offerings:
            for _item_offerings in self.offerings:
                if _item_offerings:
                    _items.append(_item_offerings.to_dict())
            _dict['offerings'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceProfileLastMileProductCatalog from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "webUrl": obj.get("webUrl"),
            "deliveryDate": ServiceProfileLastMileDeliveryDateRange.from_dict(obj["deliveryDate"]) if obj.get("deliveryDate") is not None else None,
            "offerings": [ServiceProfileLastMileOffering.from_dict(_item) for _item in obj["offerings"]] if obj.get("offerings") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


