# coding: utf-8

"""
    Equinix Fabric API v4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ServiceProfileLastMileApiIntegration(BaseModel):
    """
    Last-mile API integration details.
    """ # noqa: E501
    site_validation_enabled: Optional[StrictBool] = Field(default=None, description="Whether site validation is enabled for the last-mile provider.", alias="siteValidationEnabled")
    data_center_location_enabled: Optional[StrictBool] = Field(default=None, description="Whether data center location is enabled for the last-mile provider.", alias="dataCenterLocationEnabled")
    product_offering_enabled: Optional[StrictBool] = Field(default=None, description="Whether product offering is enabled for the last-mile provider.", alias="productOfferingEnabled")
    poq_enabled: Optional[StrictBool] = Field(default=None, description="Whether product qualification is enabled for the last-mile provider.", alias="poqEnabled")
    quote_enabled: Optional[StrictBool] = Field(default=None, description="Whether quote generation is enabled for the last-mile provider.", alias="quoteEnabled")
    place_order_enabled: Optional[StrictBool] = Field(default=None, description="Whether place order is enabled for the last-mile provider.", alias="placeOrderEnabled")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["siteValidationEnabled", "dataCenterLocationEnabled", "productOfferingEnabled", "poqEnabled", "quoteEnabled", "placeOrderEnabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceProfileLastMileApiIntegration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceProfileLastMileApiIntegration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "siteValidationEnabled": obj.get("siteValidationEnabled"),
            "dataCenterLocationEnabled": obj.get("dataCenterLocationEnabled"),
            "productOfferingEnabled": obj.get("productOfferingEnabled"),
            "poqEnabled": obj.get("poqEnabled"),
            "quoteEnabled": obj.get("quoteEnabled"),
            "placeOrderEnabled": obj.get("placeOrderEnabled")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


