on:
  pull_request_target:
    paths:
    - 'config/**'
    - 'equinix_metal/**'
    - 'templates/**'
    - metal_openapi.fixed.yaml
    - 'oas3.stitched/**'
    - 'oas3.fetched/**'
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read

env:
  COLLECTION_PATH: .ansible/collections/ansible_collections/equinix/cloud

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  integration-test-pr:
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - name: update packages
        run: sudo apt-get update -y

      - name: install make
        run: sudo apt-get install -y build-essential

      - name: checkout Python SDK, this PR
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: setup python 3
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version-file: .python-version

      - name: checkout Ansible collection
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          repository: equinix-labs/ansible-collection-equinix
          path: ${{ env.COLLECTION_PATH }}
          ref: main

      - name: install dependencies of ansible collection
        run: pip3 install -r requirements-dev.txt -r requirements.txt
        working-directory: ${{ env.COLLECTION_PATH }}

      - name: install collection
        run: make install
        working-directory: ${{ env.COLLECTION_PATH }}

      - name: install cloned Python SDK
        run: python3 -m pip install .

      - name: replace existing keys
        run: rm -rf ~/.ansible/test && mkdir -p ~/.ansible/test && ssh-keygen -m PEM -q -t rsa -N '' -f ~/.ansible/test/id_rsa
        working-directory: ${{ env.COLLECTION_PATH }}

      - name: run tests in ansible collection directory
        run: make testall
        working-directory: ${{ env.COLLECTION_PATH }}
        env:
          METAL_AUTH_TOKEN: ${{ secrets.METAL_AUTH_TOKEN }}
          ANSIBLE_ACC_METAL_DEDICATED_CONNECTION_ID: ${{ secrets.ANSIBLE_ACC_METAL_DEDICATED_CONNECTION_ID }}
