name: Generate Next Release
# This workflow will generate changelog and release notes.

on:
  workflow_dispatch:

env:
  DIST_DIR: dist
jobs:
  release:
    name: Create next release
    runs-on: ubuntu-latest

    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      new_release_git_tag: ${{ steps.release.outputs.new_release_git_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Create GitHub release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: equinix-labs@auto-commit-workflow
          GIT_AUTHOR_EMAIL: bot@equinix.noreply.github.com
          GIT_COMMITTER_NAME: equinix-labs@auto-commit-workflow
          GIT_COMMITTER_EMAIL: bot@equinix.noreply.github.com
          RELEASE_REQUESTER: "@${{ github.event.sender.login }}"

  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.new_release_published == 'true'

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ needs.release.outputs.new_release_git_tag }}"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir ${{ env.DIST_DIR }} .

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ env.DIST_DIR }}
